export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL'

export const STUDENT_DETAIL_REQUEST = 'STUDENT_DETAIL_REQUEST'
export const STUDENT_DETAIL_SUCCESS = 'STUDENT_DETAIL_SUCCESS'
export const STUDENT_DETAIL_FAIL = 'STUDENT_DETAIL_FAIL'

export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST'
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL'
export const STUDENT_UPDATE_RESET = 'STUDENT_UPDATE_RESET'

export const STUDENT_CREATE_REQUEST = 'STUDENT_CREATE_REQUEST'
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS'
export const STUDENT_CREATE_FAIL = 'STUDENT_CREATE_FAIL'
export const STUDENT_CREATE_RESET = 'STUDENT_CREATE_RESET'

export const STUDENT_DELETE_REQUEST = 'STUDENT_DELETE_REQUEST'
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS'
export const STUDENT_DELETE_FAIL = 'STUDENT_DELETE_FAIL'
export const STUDENT_DELETE_RESET = 'STUDENT_DELETE_RESET'